// JavaScript function that allows the game to be played.
    function playEvenOdd(){
        let userChoice = document.getElementById("choice").value;
        let number = Math.floor(Math.random() * 10) + 1;
        //Get the random number generated by computer and check if remainder is 0 
        let resultType = (number %2 === 0)? "even" : "odd";
        let message = "Computer picked: <strong>" + number + "</strong> ("+ resultType +")<br>";
        if(userChoice === resultType){
            message+= "You win!";
        } else {
            message+= "You lose!";
        }
        document.getElementById("output").innerHTML = message;
    }